"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.keymap]]
    on   = "<C-c>"
    run  = "yank"
    desc = "複製"

[[mgr.keymap]]
    on   = "<C-x>"
    run  = "yank --cut"
    desc = "剪切"

[[mgr.keymap]]
    on   = "v"
    run  = "paste"
    desc = "粘貼"

[[mgr.keymap]]
    on   = "x"
    run  = "unyank"
    desc = "取消已複製狀態"

[[mgr.keymap]]
    on   = "-"
    run  = "link"
    desc = "為已複製的文件創建絕對路徑的符號鏈接"

[[mgr.keymap]]
    on   = "_"
    run  = "link --relative"
    desc = "為已複製的文件創建相對路徑的符號鏈接"

[[mgr.keymap]]
    on   = "<C-->"
    run  = "hardlink"
    desc = "為已複製的文件創建硬鏈接"

[[mgr.keymap]]
    on   = "d"
    run  = "remove"
    desc = "將所選文件移動到回收站"

[[mgr.keymap]]
    on   = "D"
    run  = "remove --permanently"
    desc = "永久刪除所選文件"

[[mgr.keymap]]
    on   = "a"
    run  = "create"
    desc = "創建文件（以 / 結尾表示目錄）"

[[mgr.keymap]]
    on   = "r"
    run  = "rename --cursor=before_ext"
    desc = "重命名所選文件"

[[mgr.keymap]]
    on   = ";"
    run  = "plugin custom-shell nu -- auto --interactive"
    desc = "運行 shell 命令"

[[mgr.keymap]]
    on   = "<Space>"
    run  = "toggle"
    desc = "切換當前選擇狀態"
[[mgr.keymap]]
    on   = "<C-Space>"
    run  = "plugin command"
    desc = "yazi命令提示符"

[[mgr.keymap]]
    on = [
        "c",
        "c",
    ]
    run = "copy path"
    desc = "複製文件路徑"

[[mgr.keymap]]
    on = [
        "c",
        "d",
    ]
    run = "copy dirname"
    desc = "複製目錄路徑"

[[mgr.keymap]]
    on = [
        "c",
        "f",
    ]
    run = "copy filename"
    desc = "複製文件名"

[[mgr.keymap]]
    on = [
        "c",
        "n",
    ]
    run = "copy name_without_ext"
    desc = "複製不帶擴展名的文件名"

[[mgr.keymap]]
    desc = "開始書籤"
    on   = "g"
    run  = "plugin bunny"

[[mgr.keymap]]
    on   = "f"
    run  = "filter --smart"
    desc = "過濾文件"

[[mgr.keymap]]
    on   = "<t>"
    run  = "tab_create --current"
    desc = "創建新選項卡"

[[mgr.keymap]]
    on  = "1"
    run = "tab_switch 0"

[[mgr.keymap]]
    on  = "2"
    run = "tab_switch 1"

[[mgr.keymap]]
    on  = "3"
    run = "tab_switch 2"

[[mgr.keymap]]
    on  = "4"
    run = "tab_switch 3"

[[mgr.keymap]]
    on  = "5"
    run = "tab_switch 4"

[[mgr.keymap]]
    on  = "6"
    run = "tab_switch 5"

[[mgr.keymap]]
    on  = "7"
    run = "tab_switch 6"

[[mgr.keymap]]
    on  = "8"
    run = "tab_switch 7"

[[mgr.keymap]]
    on  = "9"
    run = "tab_switch 8"

[[mgr.keymap]]
    on  = "0"
    run = "tab_switch 9"

[[mgr.keymap]]
    on   = "<Esc>"
    run  = "escape"
    desc = "退出可視模式、清除選擇或取消搜索"

[[mgr.keymap]]
    on   = "q"
    run  = "close"
    desc = "關閉目前標籤頁"

[[mgr.keymap]]
    on   = "Q"
    run  = "quit"
    desc = "退出進程"

[[mgr.keymap]]
    on   = "<C-q>"
    run  = "quit --no-cwd-file"
    desc = "退出而不輸出 cwd 文件"

[[mgr.keymap]]
    on   = "<Up>"
    run  = "arrow prev"
    desc = "上一個文件"

[[mgr.keymap]]
    on   = "<Down>"
    run  = "arrow next"
    desc = "下一個文件"

[[mgr.keymap]]
    on   = "<PageUp>"
    run  = "arrow -100%"
    desc = "將光標向上移動一頁"

[[mgr.keymap]]
    on   = "<PageDown>"
    run  = "arrow 100%"
    desc = "將光標向下移動一頁"

[[mgr.keymap]]
    on   = "<Home>"
    run  = "arrow top"
    desc = "轉到頂部"

[[mgr.keymap]]
    on   = "<End>"
    run  = "arrow bot"
    desc = "轉到底部"

[[mgr.keymap]]
    on   = "<Left>"
    run  = "leave"
    desc = "返回父目錄"

[[mgr.keymap]]
    on = "<Space>"
    run = [
        "toggle",
        "arrow 1",
    ]
    desc = "切換當前選擇狀態"

[[mgr.keymap]]
    on   = "<C-a>"
    run  = "toggle_all --state=on"
    desc = "選擇所有文件"

[[mgr.keymap]]
    on   = "<Tab>"
    run  = "spot"
    desc = "點懸停文件"

[[mgr.keymap]]
    on   = "<Right>"
    run  = "enter"
    desc = "進入子目錄"

[[mgr.keymap]]
    on   = "<Enter>"
    run  = "plugin augment-command -- enter"
    desc = "進入子目錄/打開文件"

[[mgr.keymap]]
    on   = "<S-Enter>"
    run  = "plugin augment-command -- enter --interactive"
    desc = "進入子目錄/以交互方式打開選定的文件"

[[mgr.keymap]]
    on   = "w"
    run  = "tasks:show"
    desc = "顯示任務管理器"

[[mgr.keymap]]
    on   = "<F1>"
    run  = "help"
    desc = "打開幫助"

[[cmp.keymap]]
    on   = "<C-c>"
    run  = "close"
    desc = "取消完成"

[[cmp.keymap]]
    on   = "<Tab>"
    run  = "close --submit"
    desc = "提交完成"

[[cmp.keymap]]
    on = "<Enter>"
    run = [
        "close --submit",
        "input:close --submit",
    ]
    desc = "完成並提交輸入"

[[cmp.keymap]]
    on   = "<Up>"
    run  = "arrow prev"
    desc = "上一項"

[[cmp.keymap]]
    on   = "<Down>"
    run  = "arrow next"
    desc = "下一項"

[[cmp.keymap]]
    on   = "<F1>"
    run  = "help"
    desc = "打開幫助"

[[confirm.keymap]]
    on   = "<Esc>"
    run  = "close"
    desc = "取消確認"

[[confirm.keymap]]
    on   = "<Enter>"
    run  = "close --submit"
    desc = "提交確認"

[[confirm.keymap]]
    on   = "n"
    run  = "close"
    desc = "取消確認"

[[confirm.keymap]]
    on   = "y"
    run  = "close --submit"
    desc = "提交確認"

[[confirm.keymap]]
    on   = "<Up>"
    run  = "arrow prev"
    desc = "上一行"

[[confirm.keymap]]
    on   = "<Down>"
    run  = "arrow next"
    desc = "下一行"

[[confirm.keymap]]
    on   = "<F1>"
    run  = "help"
    desc = "打開幫助"

[[help.keymap]]
    on   = "<Esc>"
    run  = "escape"
    desc = "清除過濾或隱藏幫助"

[[help.keymap]]
    on   = "q"
    run  = "escape"
    desc = "清除過濾或隱藏幫助"

[[help.keymap]]
    on   = "<Up>"
    run  = "arrow prev"
    desc = "上一行"

[[help.keymap]]
    on   = "<Down>"
    run  = "arrow next"
    desc = "下一行"

[[help.keymap]]
    on   = "f"
    run  = "filter"
    desc = "過濾幫助內容"

[[input.keymap]]
    on   = "<Enter>"
    run  = "close --submit"
    desc = "提交輸入"

[[input.keymap]]
    on   = "<Esc>"
    run  = "escape"
    desc = "返回正常模式,或取消輸入"

[[input.keymap]]
    on   = "<Left>"
    run  = "move -1"
    desc = "向後移動一個字符"

[[input.keymap]]
    on   = "<Right>"
    run  = "move 1"
    desc = "向前移動一個字符"

[[input.keymap]]
    on   = "<C-Left>"
    run  = "backward"
    desc = "移回到當前或上一個單詞的開頭"

[[input.keymap]]
    on   = "<C-Right>"
    run  = "forward --end-of-word"
    desc = "向前移動到當前或下一個單詞的末尾"

[[input.keymap]]
    on   = "<Home>"
    run  = "move bol"
    desc = "移至 BOL"

[[input.keymap]]
    on   = "<End>"
    run  = "move eol"
    desc = "移至 EOL"

[[input.keymap]]
    on   = "<Backspace>"
    run  = "backspace"
    desc = "刪除光標前的字符"

[[input.keymap]]
    on   = "<Delete>"
    run  = "backspace --under"
    desc = "刪除光標下的字符"

[[input.keymap]]
    on   = "<C-Backspace>"
    run  = "kill backward"
    desc = "向後殺到當前單詞的開頭"

[[input.keymap]]
    on   = "<C-Delete>"
    run  = "kill forward"
    desc = "前進殺到當前單詞的末尾"

[[input.keymap]]
    on   = "<C-z>"
    run  = "undo"
    desc = "撤消"

[[input.keymap]]
    on   = "<F1>"
    run  = "help"
    desc = "打開幫助"

[[pick.keymap]]
    on   = "<Esc>"
    run  = "close"
    desc = "取消選擇"

[[pick.keymap]]
    on   = "<Enter>"
    run  = "close --submit"
    desc = "提交選擇"

[[pick.keymap]]
    on   = "<Up>"
    run  = "arrow prev"
    desc = "上一個選項"

[[pick.keymap]]
    on   = "<Down>"
    run  = "arrow next"
    desc = "下一個選項"

[[pick.keymap]]
    on   = "<F1>"
    run  = "help"
    desc = "打開幫助"

[[spot.keymap]]
    on   = "<Esc>"
    run  = "close"
    desc = "關閉 spot"

[[spot.keymap]]
    on   = "<Tab>"
    run  = "close"
    desc = "關閉 spot"

[[spot.keymap]]
    on   = "<Up>"
    run  = "arrow prev"
    desc = "上一行"

[[spot.keymap]]
    on   = "<Down>"
    run  = "arrow next"
    desc = "下一行"

[[spot.keymap]]
    on   = "<Left>"
    run  = "swipe prev"
    desc = "滑動到上一個文件"

[[spot.keymap]]
    on   = "<Right>"
    run  = "swipe next"
    desc = "滑動到下一個文件"

[[spot.keymap]]
    on   = "<F1>"
    run  = "help"
    desc = "打開幫助"

[[tasks.keymap]]
    on   = "<Esc>"
    run  = "close"
    desc = "關閉任務管理器"

[[tasks.keymap]]
    on   = "w"
    run  = "close"
    desc = "關閉任務管理器"

[[tasks.keymap]]
    on   = "<Up>"
    run  = "arrow prev"
    desc = "上一個任務"

[[tasks.keymap]]
    on   = "<Down>"
    run  = "arrow next"
    desc = "下一個任務"

[[tasks.keymap]]
    on   = "<Enter>"
    run  = "inspect"
    desc = "檢查任務"

[[tasks.keymap]]
    on   = "x"
    run  = "cancel"
    desc = "取消任務"

[[tasks.keymap]]
    on   = "<F1>"
    run  = "help"
    desc = "打開幫助"

[[mgr.keymap]]
    on   = "<S-Down>"
    run  = "seek 1"
    desc = "捲動預覽面板向下"
[[mgr.keymap]]
    on   = "<S-Up>"
    run  = "seek -1"
    desc = "捲動預覽面板向上"

    # [[mgr.keymap]]
    #     on   = "F"
    #     run  = "plugin jump-to-char"
    #     desc = "跳轉到字符"

[[mgr.keymap]]
    on   = "F"
    run  = "plugin fg -- fzf"
    desc = "按文件名查找文件"
