sequential                 = false
pipeline_placement         = "start"
max_pipeline_length        = 80
skip_external_parse_errors = true
explicit_optional_access   = false

[groups]

[rules]
    # id = "off|hint|warning|error"
    unchecked_cell_path_index   = "hint"
    max_positional_params       = "off"
    redundant_nu_subprocess     = "warning"
    pipe_spacing                = "off"
    non_final_failure_check     = "hint"
    unchecked_get_index         = "hint"
    wrap_external_with_complete = "hint"
    catch_builtin_error_try     = "hint"
