"$schema" = 'https://starship.rs/config-schema.json'

format       = "$time$all"
right_format = "$shlvl$cmd_duration$battery"

[character]
    success_symbol = "[â¯](bold green)"
    error_symbol   = "[! â¯](bold red)"

[battery]
    full_symbol        = "â€¢ "
    charging_symbol    = "â‡¡ "
    discharging_symbol = "â‡£ "
    unknown_symbol     = "â“ "
    empty_symbol       = "â— "
    disabled           = false
    [[battery.display]]
        threshold = 50

[erlang]
    symbol = "â“” "

[nodejs]
    symbol = "[â¬¢](bold green) "

[pulumi]
    symbol = "ğŸ§Š "

[typst]
    symbol = "t "

[shlvl]
    disabled = false
[git_metrics]
    disabled = false

[directory]
    truncation_length = 5
    truncation_symbol = ".../"

[time]
    disabled = false
    time_format = "%R"
